"""
display_gate — the "smartness layer" that runs on every dashboard payload
                 *just before* it is shipped to the UI.

Philosophy
----------
The dashboard is meant to be *conclusive*, not a data dump. Raw pandas /
parser output frequently contains rows that are either:

    • parser-noise   — pandas-Series repr leaks, ``NaN`` placeholders,
                       autogenerated ``Row_<idx>`` batch names, blank
                       schedule + blank window;
    • magnitude-noise — sub-minute "regressions" of a few seconds that
                       crossed a z-score threshold but carry no business
                       meaning;
    • contradiction  — outliers reported when compliance is 100 % with
                       zero breaches; ceilings of 0.0 h; etc.

Each tab payload is funnelled through ``gate(payload, kind=...)`` which:

    1. removes structurally-invalid rows,
    2. enforces minimum-magnitude thresholds,
    3. resolves contradictions between summary KPIs and detail rows,
    4. attaches a ``_gate`` audit block recording what was dropped and why,
       so the UI can show a "smart layer cleaned X rows" badge instead of
       silently lying.

Design notes
------------
* No LLM round-trip in the hot path — this layer is deterministic and
  fast. The ``narrate`` / agent layer can still annotate after.
* The gate is *additive*: it never invents data. It only filters and
  flags. If you want the LLM to *fix* data, do it upstream in the parser.
* Each ``kind`` has its own validator. Add new ones as tabs are wired in.
"""
from __future__ import annotations

from typing import Any, Dict, List

# Magnitude floors shared with services.job_baselines
_MIN_RUNTIME_HRS  = 0.10   # 6 min
_MIN_EXPECTED_HRS = 0.10
_MIN_DELTA_HRS    = 0.10


# ── Row-level validators ─────────────────────────────────────────────────────

def _is_pandas_repr_leak(s: Any) -> bool:
    """True when a string carries a pandas Series/DataFrame repr."""
    if not isinstance(s, str):
        return False
    return ("dtype:" in s and "Name:" in s) or ("\n" in s and "NaN" in s)


# Patterns that indicate a "batch_name" cell is actually a date / timestamp /
# day-of-week / runtime label that leaked from a secondary table mid-sheet.
import re as _re
_DATE_LIKE = _re.compile(
    r"^("
    r"\d{4}-\d{2}-\d{2}([ T]\d{1,2}:\d{2}(:\d{2})?)?"        # 2025-06-11, 2025-06-11 00:31:21
    r"|\d{1,2}/\d{1,2}/\d{2,4}"                                # 6/11/2025
    r"|\d{1,2}:\d{2}(:\d{2})?\s*(am|pm)?"                      # 03:30 / 03:30 PM
    r"|(mon|tue|tues|wed|thu|thur|thurs|fri|sat|sun)(day)?"    # Mon / Sunday
    r"|\d+\s*hour[s]?"                                          # 1 Hour / 5 hours
    r")$",
    _re.I,
)


def _looks_like_date_or_label(s: str) -> bool:
    """True when a batch_name cell is really a date/day/duration label."""
    if not isinstance(s, str):
        return False
    s = s.strip()
    if not s:
        return False
    return bool(_DATE_LIKE.match(s))


def _valid_sla_contract(c: Dict[str, Any]) -> bool:
    """A contract is renderable only if it has a real name AND some signal."""
    name = (c.get("batch_name") or "").strip()
    if not name or _is_pandas_repr_leak(name):
        return False
    # Drop rows where the batch_name is itself a date/time/day value —
    # these are per-run history rows that leaked from a secondary table.
    if _looks_like_date_or_label(name):
        return False
    if name.lower().startswith("row_") and not c.get("schedule_raw") \
            and not c.get("sla_window_hrs") and not c.get("sla_duration_hrs"):
        return False
    has_signal = bool(
        c.get("sla_window_hrs")
        or c.get("sla_duration_hrs")
        or c.get("schedule_raw")
        or c.get("buffer_minutes")
    )
    return has_signal


def _valid_outlier(r: Dict[str, Any]) -> bool:
    """An outlier must clear all three magnitude floors."""
    try:
        hrs      = float(r.get("run_hrs", 0) or 0)
        expected = float(r.get("expected_hrs", 0) or 0)
        delta    = float(r.get("expected_margin_hrs", 0) or 0)
    except (TypeError, ValueError):
        return False
    if hrs <= 0 or expected <= 0:
        return False
    if hrs < _MIN_RUNTIME_HRS:           return False
    if expected < _MIN_EXPECTED_HRS:     return False
    if delta < _MIN_DELTA_HRS:           return False
    return True


# ── Gate kinds ───────────────────────────────────────────────────────────────

def _gate_sla_matrix(payload: Dict[str, Any]) -> Dict[str, Any]:
    audit = {"dropped": {}, "rules": []}

    # 1. Outliers — drop magnitude-noise rows.
    raw = list(payload.get("outliers") or [])
    kept = [r for r in raw if _valid_outlier(r)]
    if len(raw) != len(kept):
        audit["dropped"]["outliers"] = len(raw) - len(kept)
        audit["rules"].append(
            f"outliers: kept {len(kept)} / {len(raw)} after magnitude floor "
            f"(run≥{_MIN_RUNTIME_HRS}h, expected≥{_MIN_EXPECTED_HRS}h, "
            f"delta≥{_MIN_DELTA_HRS}h)"
        )
    payload["outliers"] = kept or None

    # 2. Resource-linked rows — same floor; drop noise.
    raw = list(payload.get("resource_linked") or [])
    kept = [r for r in raw if _valid_outlier(r) or r.get("is_sla_breach")]
    if len(raw) != len(kept):
        audit["dropped"]["resource_linked"] = len(raw) - len(kept)
    payload["resource_linked"] = kept or None

    # 3. Contradiction guard — if compliance is 100 % AND zero breaches,
    # outliers can still exist (they're under-SLA but over-baseline). But
    # if BOTH the baseline list is empty AND the breach list is empty, we
    # should not show "X CRITICAL · Y TOTAL" headers downstream.
    if not payload.get("breaches") and not payload.get("outliers"):
        audit["rules"].append("no breaches and no outliers — clean run")

    payload["_gate"] = audit
    return payload


def _gate_sla_intel(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Filter contracts in the SLA-file intelligence panel."""
    audit = {"dropped": {}, "rules": []}
    raw = list(payload.get("contracts") or [])
    kept = [c for c in raw if _valid_sla_contract(c)]
    if len(raw) != len(kept):
        audit["dropped"]["contracts"] = len(raw) - len(kept)
        audit["rules"].append(
            f"contracts: kept {len(kept)} / {len(raw)} — removed parser-noise "
            "rows (NaN names, Series-repr leaks, autogen Row_<idx> placeholders)"
        )
    payload["contracts"] = kept

    # Re-derive valid/partial counts from the cleaned set.
    valid   = sum(1 for c in kept if c.get("completeness") == "complete")
    partial = sum(1 for c in kept if c.get("completeness") == "partial")
    payload["valid_rows"]   = valid
    payload["partial_rows"] = partial

    payload["_gate"] = audit
    return payload


# ── Public entry point ───────────────────────────────────────────────────────

_GATES = {
    "sla_matrix": _gate_sla_matrix,
    "sla_intel":  _gate_sla_intel,
}


def gate(payload: Any, *, kind: str) -> Any:
    """Run the smartness gate for a given payload kind. Safe no-op on errors."""
    if not isinstance(payload, dict):
        return payload
    fn = _GATES.get(kind)
    if not fn:
        return payload
    try:
        return fn(payload)
    except Exception as exc:  # noqa: BLE001
        import logging
        logging.getLogger("pe_dashboard.display_gate").debug(
            "gate %s skipped: %s", kind, exc,
        )
        return payload
